export const ACTIONS = {
  EXTRACT_PAGE: 'EXTRACT_PAGE',
  GET_PAGE_META: 'GET_PAGE_META',
  SAVE_BOOKMARK: 'SAVE_BOOKMARK',
  DELETE_BOOKMARK: 'DELETE_BOOKMARK',
  GET_BOOKMARK: 'GET_BOOKMARK',
  GET_BOOKMARKS: 'GET_BOOKMARKS',
  SEARCH_BOOKMARKS: 'SEARCH_BOOKMARKS',
  GET_TAGS: 'GET_TAGS',
  GET_CATEGORIES: 'GET_CATEGORIES',
  EXPORT_DATA: 'EXPORT_DATA',
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  AI_TAGS_READY: 'AI_TAGS_READY',
  BOOKMARK_UPDATED: 'BOOKMARK_UPDATED',
  API_KEY_STATUS: 'API_KEY_STATUS',
};

export function success(data) {
  return { ok: true, data };
}

export function error(message, code = 'UNKNOWN') {
  return { ok: false, error: message, code };
}
