export const ACTIONS = {
  EXTRACT_PAGE: 'EXTRACT_PAGE',
  GET_PAGE_META: 'GET_PAGE_META',
  SAVE_BOOKMARK: 'SAVE_BOOKMARK',
  UPDATE_BOOKMARK: 'UPDATE_BOOKMARK',
  DELETE_BOOKMARK: 'DELETE_BOOKMARK',
  GET_BOOKMARK:        'GET_BOOKMARK',
  GET_BOOKMARKS:       'GET_BOOKMARKS',
  SEARCH_BOOKMARKS: 'SEARCH_BOOKMARKS',
  GET_TAGS: 'GET_TAGS',
  CREATE_TAG: 'CREATE_TAG',
  DELETE_TAG: 'DELETE_TAG',
  GET_CATEGORIES: 'GET_CATEGORIES',
  PROCESS_AI_TAGS: 'PROCESS_AI_TAGS',
  EXPORT_DATA: 'EXPORT_DATA',
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  PAGE_DATA_READY: 'PAGE_DATA_READY',
  AI_TAGS_READY: 'AI_TAGS_READY',
  SYNC_STATUS: 'SYNC_STATUS',
  BOOKMARK_UPDATED: 'BOOKMARK_UPDATED',
};

export function success(data) {
  return { ok: true, data };
}

export function error(message, code = 'UNKNOWN') {
  return { ok: false, error: message, code };
}
